### ISSUE TITLE
NAMESPACE

### ISSUE THREAD

**Issue by alexdum** [pacificclimate/climdex.pcic.ncdf#2]
Apparently, the 'NAMESPACE' file of the package is missing.

**Comment by jameshiebert** [comment]
The `NAMESPACE` file is absent from the git repository, because it it auto-generated by `roxygen2`. If you get the built [package tarball of the latest release] (www.pacificclimate.org/~bronaugh/climdex.pcic.ncdf_0.5-4.tar.gz) from our website, the `NAMESPACE` file is included.
