### ISSUE TITLE
climdex.pcic.ncdf-0.5-4-0

### ISSUE THREAD

**Issue by cbchisanga** [pacificclimate/climdex.pcic.ncdf#3]
Can someone assist, am having problems to install climdex.pcic.ncdf on R-3.2

Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing to library ‘/home/cchisanga/R/x86_64-pc-linux-gnu-library/3.2’
* installing *source* package ‘climdex.pcic.ncdf’ ...
ERROR: a 'NAMESPACE' file is required
* removing ‘/home/cchisanga/R/x86_64-pc-linux-gnu-library/3.2/climdex.pcic.ncdf’

**Comment by jameshiebert** [comment]
First [build the docs](https://github.com/pacificclimate/climdex.pcic.ncdf/blob/master/CONTRIBUTING.rst#how-to-build-the-docs) with `roxygen2`. This automatically generates the `NAMESPACE` file.
