### ISSUE TITLE
Broken URL for package tarball

### ISSUE THREAD

**Issue by niteshshrestha** [pacificclimate/climdex.pcic.ncdf#4]
Hi There,

Everytime, I try to install the packages, it says like "not available for R version 3.3.2). As per the website, while checking the library, it gives "error in library, no such package found". 

This is great package, I really look forward to using it. Hence I humbly request you for your valuable support. If possible, manual also would be great help.

**Comment by jameshiebert** [comment]
Yes, it looks like [our docs](http://pacificclimate.github.io/climdex.pcic.ncdf/) instruct users to download the package tarball [from here](https://www.pacificclimate.org/~bronaugh/climdex.pcic.ncdf_0.5-4.tar.gz), but our URL is broken. Sorry about that! We'll get the tarball put up in the [PCIC website](https://pacificclimate.org) in the near future.
