### ISSUE TITLE
climdex.pcic.ncdf uninstallable via `devtools::install_github`

### ISSUE THREAD

**Issue by cphotiadou** [pacificclimate/climdex.pcic.ncdf#5]
Hi James

the NAMESPACE file is missing for the install_github process 
exportPattern( "." )

**Comment by jameshiebert** [comment]
Hi @cphotiadou! It's not exactly that the NAMESPACE file is *missing*, but that it gets automatically generated with `roxygen2::roxygenize()`. I've "solved" this (i.e. made it possible to use `install_github`) in other repositories, by maintaining a release branch that contains all of the autogenerated files (docs and the NAMESPACE). I can d othat with `climdex.pcic.ncdf`, too, but I won't be getting to it until next week.

Stay tuned, though. I'll close this issue when that's ready.

**Comment by jameshiebert** [comment]
Sorry that this got dropped on the floor. I've created a release branch now, so you should be able to do a: ``devtools::install_github('pacificclimate/climdex.pcic.ncdf', ref='release')`` and always get the latest release. Cheers.
