### ISSUE TITLE
I can not install libs: udunits2  and proj4 necessary for the tool

### ISSUE THREAD

**Issue by aniszammel** [pacificclimate/climdex.pcic.ncdf#8]

**Comment by jameshiebert** [comment]
Need more info from you.

**Comment by aniszammel** [comment]
When I tried to install udunits i got the following error:

-----Error: udunits2.h not found-----
     If the udunits2 library is installed in a non-standard location,
     use --configure-args='--with-udunits2-lib=/usr/local/lib' for example,
     or --configure-args='--with-udunits2-include=/usr/include/udunits2'
     replacing paths with appropriate values for your installation.
     You can alternatively use the UDUNITS2_INCLUDE and UDUNITS2_LIB
     environment variables.
     If udunits2 is not installed, please install it.
     It is required for this package.
ERROR: configuration failed for package ‘udunits2’

**Comment by jameshiebert** [comment]
udunits2 R package declares a [SystemRequirements](https://github.com/pacificclimate/Rudunits2/blob/master/DESCRIPTION#L9) which, [by definition](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#The-DESCRIPTION-file), has to be dealt with outside of the R packaging environment.

Describing how to do that, depends on your operating system and other factors and is somewhat outside of the scope of this package. HOwever, you may want to review [this issue](https://github.com/edzer/units/issues/1) to see how others have handled it.

**Comment by aniszammel** [comment]
I did those all steps but the error still the same. I used Fedora 23 (64bit) and  R version 3.3.1.

**Comment by jameshiebert** [comment]
``yum install udunits2-devel``?

**Comment by aniszammel** [comment]
yes I use this command.
Already i used: yum install udunits2.x86_64

**Comment by jameshiebert** [comment]
You need to install the ``-devel`` package. It contains the header files asked for in your error message above.

**Comment by aniszammel** [comment]
yes i installed but the error still.

**Comment by jameshiebert** [comment]
Sorry, @aniszammel I think that you will need help from your own company's tech support. This is out-of-scope of the ``climdex.pcic.ncdf`` package and I don't think that I can help you.
