### ISSUE TITLE
How I prepare my information to work with the climdex.pcic.ncdf package!

### ISSUE THREAD

**Issue by AlvaroAvila360** [pacificclimate/climdex.pcic.ncdf#9]
Hello Everybody,
I am trying to compute my data in the climdex.pcic.ncdf package, But I have problems because I don't have the information in the proper format. 

In this sense, how I prepare my information to work with the  climdex.pcic.ncdf package?

Thank you!

**Comment by corviday** [comment]
Do you mean your data isn't in the netCDF file format and you're not sure how to convert it? 

Or do you mean that your data is in the netCDF file format, but that something isn't working or there's an error message when you try to use this package? If so, can you give more about exactly what happens when you try to run it?

**Comment by AlvaroAvila360** [comment]
Hello, 
My data is in the netCDF file format, I guess the error is in the number of dimensions on my file.nc, but I'm not sure.

An error message is:
Error in names(fn.split) <- c("var", "tres", "model", "emissions", "run",  : 
  'names' attribute [6] must be the same length as the vector [2]

This the main information of my file.nc
dimensions:
	longitude = 167 ;
	latitude = 161 ;
	time = UNLIMITED ; // (1827 currently)
variables:
	float longitude(longitude) ;
		longitude:standard_name = "longitude" ;
		longitude:long_name = "longitude" ;
		longitude:units = "degree_east" ;
		longitude:axis = "X" ;
	float latitude(latitude) ;
		latitude:standard_name = "latitude" ;
		latitude:long_name = "latitude" ;
		latitude:units = "degree_north" ;
		latitude:axis = "Y" ;
	double time(time) ;
		time:standard_name = "time" ;
		time:units = "days since 1985-1-1 00:00:00" ;
		time:calendar = "standard" ;
		time:axis = "T" ;
	float pr(time, latitude, longitude) ;
		pr:standard_name = "precipitation" ;
		pr:units = "mm" ;
		pr:_ChunkSizes = 3653, 162, 168 ;

**Comment by corviday** [comment]
I'm not very familiar with this package, but I think this might be an issue with the name of your netCDF file. I believe this package expects files to be named according to the [CMIP5 data reference standards (see section 3.3)](http://cmip-pcmdi.llnl.gov/cmip5/docs/cmip5_data_reference_syntax.pdf). So it should have a name something like this:

> variable_timeresolution_model_emissionscenario_ensemblemember.nc 

Your variable is `pr` for precipitation, and it looks like your resolution is probably 'day', so your filename should start `pr_day_`, but I don't know what model or emissions scenario you're using. 

Try renaming your netCDF file and see if that helps.

**Comment by corviday** [comment]
I haven't heard anything in a while, so I'm closing this issue. Feel free to post again if you have any other trouble.
